### ISSUE TITLE
Metabug: Technical Roadblocks to Bumping the Major Version Number

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#21055]
At various times we have discussed the idea of moving Perl's major version number onwards from 5, perhaps to 7 or later. Ignoring any discussions of why or when that might occur, and what features or alterations to the language or other ideas it might entail, there are a bunch of actual technical reasons why changing the 5 into a 7 (or higher) is not easy.

This issue intends to track the various places where the major version number (currently 5) appears, that would need some consideration about what to do with it. This isn't the place to discuss in detail any particular detail - for that, open a new issue for it. This metabug simply tracks the list of all the known ones.

- [ ] Environment Variables (`PERL5LIB`, etc)
- [ ] perl5-porters@ mailing list
- [ ] `#p5p` IRC channel
- [ ] The name of this repository

**Comment by mauke** [comment]
Github's "guess the language" code scans for `use v5`: https://github.com/github-linguist/linguist/blob/5a0c74277548122267d84283910abd5e0b89380e/lib/linguist/heuristics.yml#L835

**Comment by ilmari** [comment]
the name of this very repository

**Comment by smpeters** [comment]
p5* - a common prefix for Perl packages on Github, CPAN, Linux packages,
etc.

**Comment by leonerd** [comment]
@smpeters 
> p5* - a common prefix for Perl packages on Github, CPAN, Linux packages,

Yeah; that's true.. though I don't know if there's a lot we can do about that. We can't change those names, so at best we'd just have to ask others to do that and give some advice on what would be best.

**Comment by rwp0** [comment]
> the name of this very repository

It's usually the same for Python and Ruby and other languages as well:


Eg.

py27-
ruby31-

https://openports.pl/cat/lang/ruby

The symlinking approach to set the default one usually works.
